### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by faceleg** [angelozerr/tern-react#1]
We'd like to use this in https://github.com/ramitos/jsctags (and do), but it'd be great to be able to reference it as a normal npm module instead of a git repo.

**Comment by angelozerr** [comment]
Wow glad this tern plugin could interest you but today It doesn't work.

Any contribution are welcome

**Comment by faceleg** [comment]
Uh, seems to work ok here: https://github.com/ramitos/jsctags

**Comment by angelozerr** [comment]
Ok here the state of this plugin : I can parse code with acorn-jsx, so now AST contains JSXElement, but when you do completion it fails because tern doesn't know JSXElement but tern seems providning the capability to add their own element . See https://github.com/marijnh/tern/issues/565#issuecomment-148710233

I must test that.

> Uh, seems to work ok here: https://github.com/ramitos/jsctags

What is working?

**Comment by sergioramos** [comment]
It's not being used for autocompletion, that why it "works" ;)

**Comment by angelozerr** [comment]
> It's not being used for autocompletion, that why it "works" ;)

Ok thanks for the info. I'm OK to publish it, but I would like to say in the README that it is limitaed to only some feature. Could you create a PR in the README to explain which tern query type you are using.

Thanks!

**Comment by angelozerr** [comment]
@faceleg @ramitos I'm OK to publish tern-react. Please try the last version to check if it works in your side.

This tern plugin doesn't work (for completion) with tern 1.5.0 but it will work for 1.6.0. So I would like to say that in the README and I would like to that you explain that it can work with 1.5.0 with jsctags. Indded, otherwise people will try tern-react wiyh completion and they will not happy with tern-react (I would like to avoid that).

I'm waiting for your answer to publish tern-react.

**Comment by sergioramos** [comment]
It works for jsctags, but I understand your reservations and I'm happy to wait for tern 1.6 ;)

Right now we use it as a [github dependency](https://github.com/ramitos/jsctags/blob/master/package.json#L38) and we can leave it like that until you're confident to publish it to NPM ;)

**Comment by angelozerr** [comment]
> It works for jsctags

I have changed now tern-react, is it working again?

> I'm happy to wait for tern 1.6 ;)

@ramitos thanks for your answer. So we will wait 1.6, is it OK?

I have started to add React JSON Type Definitions and start overriding walker to support JSXElement etc for completion, etc

I don't know React/JSX, so if some people could help me, it should be fantastic. Thanks!

**Comment by sergioramos** [comment]
> So we will wait 1.6, is it OK?

Sure :)

**Comment by angelozerr** [comment]
@faceleg @ramitos I have created the release 0.1.0 of tern-react which is based on tern 0.16.0. But pay attention, it's just a POC and thera are a lot of limitation:
- compeltion doesn't work for JSXElement
- your JSX must be valid otherwise it will not work. See https://github.com/RReverser/acorn-jsx/issues/32

I have added that in the README. 

Any contribution are welcome!

**Comment by faceleg** [comment]
Thank you!
